### ISSUE TITLE
Save support

### ISSUE THREAD

**Issue by BernierCR** [thamo01/CB-Pokemon#1]
Hey, are you interested in updating this? I could fork it, or we could work together. It'd be nice to have a v2 app version with persistent storage of data and newer Pokémon.

**Comment by biggestsonicfan** [comment]
The original Pokedex has save support and a few more Pokemon, up to Sudowoodo in the National dex, but it lacks the battle feature.

**Comment by BernierCR** [comment]
That isn't open sourced so I can't work on it. I'll just fork this. 

Do you know how to contact Asudem? Maybe he would give me access to the new data and features, and I combine them all into a modern v2 app.  The v2 apps aren't just one monolithic js file, so I don't think I can make typescript work with it. Not very good with typescript. So if no one volunteers to help me with typescript, I have to put my version back into JS.

**Comment by biggestsonicfan** [comment]
I am literally Asudem.

**Comment by BernierCR** [comment]
oh cool. Are you able to delete this issue?

**Comment by biggestsonicfan** [comment]
Issues on repos don't quite work that way. We can close it, however.
